<?php

namespace ContainerYiAjGMU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCleanCommentsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CleanCommentsCommand' shared autowired service.
     *
     * @return \App\Command\CleanCommentsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CleanCommentsCommand.php';

        $container->privates['App\\Command\\CleanCommentsCommand'] = $instance = new \App\Command\CleanCommentsCommand(($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')));

        $instance->setName('app:clean-comments');

        return $instance;
    }
}
