<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYiAjGMU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYiAjGMU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYiAjGMU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYiAjGMU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYiAjGMU\App_KernelDevDebugContainer([
    'container.build_hash' => 'YiAjGMU',
    'container.build_id' => '1f3336da',
    'container.build_time' => 1613747839,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYiAjGMU');
